# Generated by Django 4.2.2 on 2023-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=400)),
            ],
        ),
    ]
